version: '3.9'
services:
  frontend:
    image: krishna1386/react:frontend
    # pull: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    # build:
    #   context: .
    #   dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"  # Map the frontend port to host
    depends_on:
      - backend
    environment:
      - NODE_ENV=production  # Set production environment


  backend:
    image: krishna1386/react:backend
    # pull: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    # build:
    #   context: .
    #   dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"  # Map the backend port to host
    environment:
      - NODE_ENV=production  # Set production environment
